# Generated by Django 3.2.5 on 2024-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240227_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcement',
            },
        ),
        migrations.AlterModelOptions(
            name='commentitems',
            options={'verbose_name': '饰品评论列表', 'verbose_name_plural': '饰品评论列表'},
        ),
    ]
