# Generated by Django 3.2.5 on 2024-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240301_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickitems',
            name='item_id',
            field=models.CharField(max_length=255, verbose_name='物品id'),
        ),
        migrations.AlterField(
            model_name='staritems',
            name='item_id',
            field=models.CharField(max_length=255, verbose_name='物品id'),
        ),
    ]
