# Generated by Django 3.2.5 on 2024-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240304_1112'),
    ]

    operations = [
        
    ]
