# Generated by Django 3.2.5 on 2024-03-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240304_1114'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clickitems',
            name='click_items_item_id_605a69_idx',
        ),
        migrations.RemoveIndex(
            model_name='staritems',
            name='star_items_item_id_2e956a_idx',
        ),
        # migrations.AddIndex(
        #     model_name='clickitems',
        #     index=models.Index(fields=['item_id', 'user_id'], name='click_items_item_id_605a69_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='staritems',
        #     index=models.Index(fields=['item_id', 'user_id'], name='star_items_item_id_2e956a_idx'),
        # ),
    ]
