# Generated by Django 3.2.5 on 2024-03-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240304_1115'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='clickitems',
        #     name='click_items_item_id_605a69_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='staritems',
        #     name='star_items_item_id_2e956a_idx',
        # ),
        migrations.AlterUniqueTogether(
            name='clickitems',
            unique_together={('item_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='staritems',
            unique_together={('item_id', 'user_id')},
        ),
    ]
