# Generated by Django 3.2.5 on 2024-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240304_1117'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='user',
            name='Inviter',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
