# Generated by Django 3.2.5 on 2024-03-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240306_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=255, verbose_name='来源')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '用户VIP积分',
                'verbose_name_plural': '用户VIP积分',
                'db_table': 'vip_points',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.AddField(
            model_name='vippoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
