# Generated by Django 3.2.5 on 2024-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240306_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsName',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='饰品名称')),
            ],
        )
    ]
