# Generated by Django 3.2.5 on 2024-03-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20240308_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsname',
            options={'verbose_name': '饰品名称', 'verbose_name_plural': '饰品名称'},
        ),
        migrations.AlterModelTable(
            name='goodsname',
            table='goods_name',
        ),
    ]
