# Generated by Django 3.2.5 on 2024-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20240308_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsname',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='饰品名称'),
        ),
    ]
