# Generated by Django 3.2.5 on 2024-03-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_goodsname_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户签到',
                'db_table': 'user_checkin',
                'unique_together': {('date', 'user_id')},
            },
        ),
    ]
