# Generated by Django 3.2.5 on 2024-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vippoints',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
