# Generated by Django 3.2.5 on 2024-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_vippoints_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsname',
            name='gid',
        ),
        migrations.AddField(
            model_name='goodsname',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='饰品分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='exterior',
            field=models.CharField(default=1, max_length=255, verbose_name='饰品磨损'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='icon_url',
            field=models.TextField(default=1, verbose_name='图片url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='item_id',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='quality',
            field=models.CharField(default=1, max_length=255, verbose_name='饰品质量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='rarity',
            field=models.CharField(default=1, max_length=255, verbose_name='饰品品质'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsname',
            name='type',
            field=models.CharField(default=1, max_length=255, verbose_name='饰品类型'),
            preserve_default=False,
        ),
    ]
