# Generated by Django 3.2.5 on 2024-03-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20240311_1342'),
    ]

    operations = [
       
    ]
