# Generated by Django 3.2.5 on 2024-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_commentitems_unique_together'),
    ]

    operations = [
       
    ]
